
name: Code Quality & Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  quality:
    runs-on: ubuntu-latest
    name: Code Quality
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ruff black
    - name: Run ruff
      run: ruff check custom_components/
    - name: Run black
      run: black --check custom_components/
      
  tests:
    runs-on: ubuntu-latest
    name: Tests
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-cov homeassistant
    - name: Run tests
      run: |
        if [ -d "tests" ] && find tests -name "test_*.py" | grep -q .; then
          pytest tests/ -v
        else
          echo "No tests found, skipping test execution"
        fi